name: Build and Deploy Minecraft Resource Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Upload resource pack
        uses: appleboy/scp-action@master
        with:
         host: ${{ secrets.MC_SERVER_IP }}
         username: ${{ secrets.MC_SERVER_USER }}
         key: ${{ secrets.MC_SERVER_SSH_KEY }}
         port: 20001
         source: "CustomResourcePack.zip"
         target: "/root/mc-server/"
         strip_components: 2


      # Install mcrcon and reload Minecraft server

      - name: Install mcrcon
        run: |
          sudo apt-get install -y git gcc make
          git clone https://github.com/Tiiffi/mcrcon.git
          cd mcrcon
          make
          sudo cp mcrcon /usr/local/bin
      
      - name: Install mcrcon and reload Minecraft server
        run: |
          mcrcon -H ${{ secrets.MC_SERVER_IP }} -P 20074 -p ${{ secrets.MC_SERVER_RCON_PASSWORD }} "say [Server] 🚨 New resource pack update! Restarting server..."
          mcrcon -H ${{ secrets.MC_SERVER_IP }} -P 20074 -p ${{ secrets.MC_SERVER_RCON_PASSWORD }} "restart"
        env:
          MC_SERVER_RCON_PASSWORD: ${{ secrets.MC_SERVER_RCON_PASSWORD }}
